server:
  port: 0 # 0으로 설정 시 0 ~ 65535중의 중복되지 않은 임의의 수로 설정

eureka:
  client:
    enabled: false

spring:
  config:
    activate:
      on-profile: local
  application:
    name: ordering-service
  redis:
    host: localhost
    port: 6379
  # 아래는 jdbc의 기본 db 관련 설정인데, jdbc 뿐만 아니라 mybatis / jpa 등 spring의 대부분의 DB 기술에 동일하게 사용
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ordermsa
    username: root
    password: 1234
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
  kafka:
    kafka-server: localhost:9092

resilience4j: # Bean 따로 안 만들고, 해당 설정으로 처리
  circuitbreaker:
    instances:
      productServiceCircuit: # 이름 커스텀 가능
        failureRateThreshold: 40  # 40% 이상의 실패율이면 OPEN 상태로 변경
        slowCallRateThreshold: 40  # 40% 이상의 요청이 느리면 OPEN 상태로 변경
        slowCallDurationThreshold: 2s  # 2초 이상 걸리면 느린호출로 간주
        waitDurationInOpenState: 10s  # OPEN 상태에서 10초 동안 차단 후 HALF-OPEN 상태로 변경
        permittedNumberOfCallsInHalfOpenState: 2  # HALF-OPEN 상태에서 2개 요청이 모두 성공하면 → CLOSED 상태로 변경
        slidingWindowSize: 5  # 최근 5개의 요청을 기준으로 실패율 계산
        slidingWindowType: COUNT_BASED  # 요청 개수를 기준으로 실패율을 계산하도록 설정
        minimumNumberOfCalls: 4  # 최소 정상적인 요청을 4번 실행된 이후 Circuit Breaker 활성화
        #        진짜로 잘못 보낸 요청의 경우에는 서킷브레이커의 기준이 되지 않도록 예외클래스 지정
        ignoreExceptions:
          - java.lang.IllegalArgumentException  # IllegalArgumentException 무시